REVOKE INSERT ON Location FROM PUBLIC;
REVOKE UPDATE ON Location FROM PUBLIC;
REVOKE DELETE ON Location FROM PUBLIC;
GRANT INSERT, UPDATE, DELETE ON Location TO db_admin;
REVOKE SELECT ON Location FROM PUBLIC;
GRANT SELECT ON Location TO db_admin;
CREATE SCHEMA restricted;
ALTER TABLE Location SET SCHEMA restricted;
GRANT SELECT ON ALL TABLES IN SCHEMA restricted TO restricted_role;