INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (1, 1, 'Team Alpha', 5);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (2, 2, 'Team Bravo', 4);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (3, 3, 'Team Charlie', 6);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (4, 4, 'Team Delta', 3);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (5, 5, 'Team Echo', 7);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (6, 6, 'Team Foxtrot', 5);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (7, 7, 'Team Golf', 4);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (8, 8, 'Team Hotel', 6);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (9, 9, 'Team India', 3);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (10, 10, 'Team Juliet', 5);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (11, 11, 'Team Kilo', 4);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (12, 12, 'Team Lima', 6);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (13, 13, 'Team Mike', 3);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (14, 14, 'Team November', 7);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (15, 15, 'Team Oscar', 5);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (16, 16, 'Team Papa', 4);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (17, 17, 'Team Quebec', 6);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (18, 18, 'Team Romeo', 3);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (19, 19, 'Team Sierra', 5);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (20, 20, 'Team Tango', 4);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (21, 21, 'Team Uniform', 5);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (22, 22, 'Team Victor', 4);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (23, 23, 'Team Whiskey', 6);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (24, 24, 'Team X-ray', 3);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (25, 25, 'Team Yankee', 7);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (26, 26, 'Team Zulu', 5);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (27, 27, 'Team Alpha Prime', 4);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (28, 28, 'Team Beta Prime', 6);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (29, 29, 'Team Gamma Prime', 3);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (30, 30, 'Team Delta Prime', 5);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (31, 31, 'Team Epsilon Prime', 4);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (32, 32, 'Team Zeta Prime', 6);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (33, 33, 'Team Eta Prime', 3);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (34, 34, 'Team Theta Prime', 7);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (35, 35, 'Team Iota Prime', 5);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (36, 36, 'Team Kappa Prime', 4);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (37, 37, 'Team Lambda Prime', 6);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (38, 38, 'Team Mu Prime', 3);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (39, 39, 'Team Nu Prime', 5);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (40, 40, 'Team Xi Prime', 4);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (41, 41, 'Team Omicron Prime', 6);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (42, 42, 'Team Pi Prime', 3);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (43, 43, 'Team Rho Prime', 7);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (44, 44, 'Team Sigma Prime', 5);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (45, 45, 'Team Tau Prime', 4);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (46, 46, 'Team Upsilon Prime', 6);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (47, 47, 'Team Phi Prime', 3);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (48, 48, 'Team Chi Prime', 5);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (49, 49, 'Team Psi Prime', 4);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (50, 50, 'Team Omega Prime', 6);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (51, 51, 'Team A', 3);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (52, 52, 'Team B', 5);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (53, 53, 'Team C', 4);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (54, 54, 'Team D', 6);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (55, 55, 'Team E', 3);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (56, 56, 'Team F', 7);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (57, 57, 'Team G', 5);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (58, 58, 'Team H', 4);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (59, 59, 'Team I', 6);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (60, 60, 'Team J', 3);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (61, 61, 'Team K', 5);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (62, 62, 'Team L', 4);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (63, 63, 'Team M', 6);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (64, 64, 'Team N', 3);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (65, 65, 'Team O', 7);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (66, 66, 'Team P', 5);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (67, 67, 'Team Q', 4);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (68, 68, 'Team R', 6);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (69, 69, 'Team S', 3);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (70, 70, 'Team T', 5);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (71, 71, 'Team U', 4);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (72, 72, 'Team V', 6);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (73, 73, 'Team W', 3);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (74, 74, 'Team X', 7);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (75, 75, 'Team Y', 5);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (76, 76, 'Team Z', 4);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (77, 77, 'Team Alpha One', 6);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (78, 78, 'Team Bravo One', 3);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (79, 79, 'Team Charlie One', 5);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (80, 80, 'Team Delta One', 4);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (81, 81, 'Team Echo One', 6);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (82, 82, 'Team Foxtrot One', 3);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (83, 83, 'Team Golf One', 5);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (84, 84, 'Team Hotel One', 4);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (85, 85, 'Team India One', 6);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (86, 86, 'Team Juliet One', 3);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (87, 87, 'Team Kilo One', 5);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (88, 88, 'Team Lima One', 4);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (89, 89, 'Team Mike One', 6);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (90, 90, 'Team November One', 3);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (91, 91, 'Team Oscar One', 5);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (92, 92, 'Team Papa One', 4);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (93, 93, 'Team Quebec One', 6);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (94, 94, 'Team Romeo One', 3);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (95, 95, 'Team Sierra One', 7);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (96, 96, 'Team Tango One', 5);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (97, 97, 'Team Uniform One', 4);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (98, 98, 'Team Victor One', 6);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (99, 99, 'Team Whiskey One', 3);
INSERT INTO Teams (Teams_id, Participant_id, teamname, quantity) VALUES (100, 100, 'Team X-ray One', 5);