INSERT INTO Location (Location_id, Locationname) VALUES (1, 'New York City');
INSERT INTO Location (Location_id, Locationname) VALUES (2, 'Los Angeles');
INSERT INTO Location (Location_id, Locationname) VALUES (3, 'London');
INSERT INTO Location (Location_id, Locationname) VALUES (4, 'Paris');
INSERT INTO Location (Location_id, Locationname) VALUES (5, 'Tokyo');
INSERT INTO Location (Location_id, Locationname) VALUES (6, 'Sydney');
INSERT INTO Location (Location_id, Locationname) VALUES (7, 'Berlin');
INSERT INTO Location (Location_id, Locationname) VALUES (8, 'Rome');
INSERT INTO Location (Location_id, Locationname) VALUES (9, 'Moscow');
INSERT INTO Location (Location_id, Locationname) VALUES (10, 'Beijing');
INSERT INTO Location (Location_id, Locationname) VALUES (11, 'Cairo');
INSERT INTO Location (Location_id, Locationname) VALUES (12, 'Mexico City');
INSERT INTO Location (Location_id, Locationname) VALUES (13, 'Toronto');
INSERT INTO Location (Location_id, Locationname) VALUES (14, 'Mumbai');
INSERT INTO Location (Location_id, Locationname) VALUES (15, 'Dubai');
INSERT INTO Location (Location_id, Locationname) VALUES (16, 'Seoul');
INSERT INTO Location (Location_id, Locationname) VALUES (17, 'Singapore');
INSERT INTO Location (Location_id, Locationname) VALUES (18, 'Hong Kong');
INSERT INTO Location (Location_id, Locationname) VALUES (19, 'Bangkok');
INSERT INTO Location (Location_id, Locationname) VALUES (20, 'São Paulo');
INSERT INTO Location (Location_id, Locationname) VALUES (21, 'Amsterdam');
INSERT INTO Location (Location_id, Locationname) VALUES (22, 'Madrid');
INSERT INTO Location (Location_id, Locationname) VALUES (23, 'Vienna');
INSERT INTO Location (Location_id, Locationname) VALUES (24, 'Athens');
INSERT INTO Location (Location_id, Locationname) VALUES (25, 'Stockholm');
INSERT INTO Location (Location_id, Locationname) VALUES (26, 'Oslo');
INSERT INTO Location (Location_id, Locationname) VALUES (27, 'Helsinki');
INSERT INTO Location (Location_id, Locationname) VALUES (28, 'Brussels');
INSERT INTO Location (Location_id, Locationname) VALUES (29, 'Budapest');
INSERT INTO Location (Location_id, Locationname) VALUES (30, 'Prague');
INSERT INTO Location (Location_id, Locationname) VALUES (31, 'Warsaw');
INSERT INTO Location (Location_id, Locationname) VALUES (32, 'Lisbon');
INSERT INTO Location (Location_id, Locationname) VALUES (33, 'Dublin');
INSERT INTO Location (Location_id, Locationname) VALUES (34, 'Bratislava');
INSERT INTO Location (Location_id, Locationname) VALUES (35, 'Zurich');
INSERT INTO Location (Location_id, Locationname) VALUES (36, 'Geneva');
INSERT INTO Location (Location_id, Locationname) VALUES (37, 'Buenos Aires');
INSERT INTO Location (Location_id, Locationname) VALUES (38, 'Santiago');
INSERT INTO Location (Location_id, Locationname) VALUES (39, 'Lima');
INSERT INTO Location (Location_id, Locationname) VALUES (40, 'Bogotá');
INSERT INTO Location (Location_id, Locationname) VALUES (41, 'Copenhagen');
INSERT INTO Location (Location_id, Locationname) VALUES (42, 'Montreal');
INSERT INTO Location (Location_id, Locationname) VALUES (43, 'Melbourne');
INSERT INTO Location (Location_id, Locationname) VALUES (44, 'Auckland');
INSERT INTO Location (Location_id, Locationname) VALUES (45, 'Hamburg');
INSERT INTO Location (Location_id, Locationname) VALUES (46, 'Barcelona');
INSERT INTO Location (Location_id, Locationname) VALUES (47, 'Edinburgh');
INSERT INTO Location (Location_id, Locationname) VALUES (48, 'Kuala Lumpur');
INSERT INTO Location (Location_id, Locationname) VALUES (49, 'Jakarta');
INSERT INTO Location (Location_id, Locationname) VALUES (50, 'Bangalore');
INSERT INTO Location (Location_id, Locationname) VALUES (51, 'Manila');
INSERT INTO Location (Location_id, Locationname) VALUES (52, 'Montevideo');
INSERT INTO Location (Location_id, Locationname) VALUES (53, 'San Francisco');
INSERT INTO Location (Location_id, Locationname) VALUES (54, 'Dubrovnik');
INSERT INTO Location (Location_id, Locationname) VALUES (55, 'Venice');
INSERT INTO Location (Location_id, Locationname) VALUES (56, 'Florence');
INSERT INTO Location (Location_id, Locationname) VALUES (57, 'Brisbane');
INSERT INTO Location (Location_id, Locationname) VALUES (58, 'Perth');
INSERT INTO Location (Location_id, Locationname) VALUES (59, 'Cape Town');
INSERT INTO Location (Location_id, Locationname) VALUES (60, 'Johannesburg');
INSERT INTO Location (Location_id, Locationname) VALUES (61, 'Munich');
INSERT INTO Location (Location_id, Locationname) VALUES (62, 'Nice');
INSERT INTO Location (Location_id, Locationname) VALUES (63, 'Rio de Janeiro');
INSERT INTO Location (Location_id, Locationname) VALUES (64, 'Vancouver');
INSERT INTO Location (Location_id, Locationname) VALUES (65, 'Toronto');
INSERT INTO Location (Location_id, Locationname) VALUES (66, 'Osaka');
INSERT INTO Location (Location_id, Locationname) VALUES (67, 'Kyoto');
INSERT INTO Location (Location_id, Locationname) VALUES (68, 'Cancun');
INSERT INTO Location (Location_id, Locationname) VALUES (69, 'Puerto Vallarta');
INSERT INTO Location (Location_id, Locationname) VALUES (70, 'Playa del Carmen');
INSERT INTO Location (Location_id, Locationname) VALUES (71, 'Cartagena');
INSERT INTO Location (Location_id, Locationname) VALUES (72, 'Santorini');
INSERT INTO Location (Location_id, Locationname) VALUES (73, 'Mykonos');
INSERT INTO Location (Location_id, Locationname) VALUES (74, 'Istanbul');
INSERT INTO Location (Location_id, Locationname) VALUES (75, 'Krakow');
INSERT INTO Location (Location_id, Locationname) VALUES (76, 'Gdansk');
INSERT INTO Location (Location_id, Locationname) VALUES (77, 'Tallinn');
INSERT INTO Location (Location_id, Locationname) VALUES (78, 'Riga');
INSERT INTO Location (Location_id, Locationname) VALUES (79, 'Valletta');
INSERT INTO Location (Location_id, Locationname) VALUES (80, 'Split');
INSERT INTO Location (Location_id, Locationname) VALUES (81, 'Granada');
INSERT INTO Location (Location_id, Locationname) VALUES (82, 'Salzburg');
INSERT INTO Location (Location_id, Locationname) VALUES (83, 'Reykjavik');
INSERT INTO Location (Location_id, Locationname) VALUES (84, 'Cairo');
INSERT INTO Location (Location_id, Locationname) VALUES (85, 'Budapest');
INSERT INTO Location (Location_id, Locationname) VALUES (86, 'Bruges');
INSERT INTO Location (Location_id, Locationname) VALUES (87, 'Cologne');
INSERT INTO Location (Location_id, Locationname) VALUES (88, 'Lyon');
INSERT INTO Location (Location_id, Locationname) VALUES (89, 'Edinburgh');
INSERT INTO Location (Location_id, Locationname) VALUES (90, 'Belfast');
INSERT INTO Location (Location_id, Locationname) VALUES (91, 'Havana');
INSERT INTO Location (Location_id, Locationname) VALUES (92, 'Siena');
INSERT INTO Location (Location_id, Locationname) VALUES (93, 'Naples');
INSERT INTO Location (Location_id, Locationname) VALUES (94, 'Amalfi');
INSERT INTO Location (Location_id, Locationname) VALUES (95, 'Pisa');
INSERT INTO Location (Location_id, Locationname) VALUES (96, 'Bologna');
INSERT INTO Location (Location_id, Locationname) VALUES (97, 'Ravenna');
INSERT INTO Location (Location_id, Locationname) VALUES (98, 'Verona');
INSERT INTO Location (Location_id, Locationname) VALUES (99, 'Florence');
INSERT INTO Location (Location_id, Locationname) VALUES (100, 'Palermo');